import React, { useState, useMemo, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '@/utils/api.js';
import toast from 'react-hot-toast';
import { Button } from '@/components/ui/Button.jsx';
import { Input } from '@/components/ui/Input.jsx';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/Select";
import { Card, CardContent } from '@/components/ui/Card.jsx';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/Tabs";
import { CalendarDays, Save, RefreshCw, Hotel, Wand2 } from 'lucide-react';

const fetchHotels = async () => (await api.get('/admin/hotels')).data;
const publishPlan = (plan) => api.post('/rooms/daily-plan', { plan });

export default function DailyPlanPage() {
    const queryClient = useQueryClient();
    
    const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
    const [selectedHotel, setSelectedHotel] = useState(null);
    const [planDraft, setPlanDraft] = useState({});

    // 1. טעינת מלונות
    const { data: hotels = [] } = useQuery({ 
        queryKey: ['hotels'], 
        queryFn: fetchHotels 
    });

    // בחירה אוטומטית של המלון הראשון
    useEffect(() => {
        if (hotels.length > 0 && !selectedHotel) {
            setSelectedHotel(hotels[0]._id);
        }
    }, [hotels]);

    // 2. טעינת נתונים חכמה: שואב את הסטטוסים מהאקסל (דרך ה-booking controller)
    const { data: roomsData = [], isLoading } = useQuery({
        queryKey: ['dailyDashboardPlan', { hotelId: selectedHotel, date: selectedDate }],
        queryFn: async () => {
            if (!selectedHotel) return [];
            // שימוש בנתיב הקיים שמחזיר את הסטטוסים המחושבים (arrival/departure/stayover)
            const { data } = await api.get(`/bookings/daily?hotelId=${selectedHotel}&date=${selectedDate}`);
            return data;
        },
        enabled: !!selectedHotel
    });

    // 3. מילוי אוטומטי (Auto-Populate) של הטופס לפי המידע מהאקסל
    useEffect(() => {
        if (roomsData.length > 0) {
            const autoDraft = {};
            roomsData.forEach(room => {
                let suggestedAction = 'none';
                
                // תרגום לוגיקה: מה המערכת ממליצה לעשות לפי האקסל?
                // אם יש עזיבה או תחלופה -> צריך להכין חדר (Checkout List + Beds)
                if (room.dashboardStatus === 'departure' || room.dashboardStatus === 'back_to_back') {
                    suggestedAction = 'checkout'; 
                } 
                // אם האורח נשאר -> ניקיון שוטף (Stayover List)
                else if (room.dashboardStatus === 'stayover') {
                    suggestedAction = 'stayover'; 
                }
                // אם יש הגעה לחדר ריק -> הכנה (Checkout List + Beds)
                else if (room.dashboardStatus === 'arrival') {
                     suggestedAction = 'arrival';
                }

                // רק אם יש פעולה מומלצת, נכניס לטיוטה
                if (suggestedAction !== 'none') {
                    autoDraft[room._id] = { 
                        action: suggestedAction, 
                        note: '',
                        autoGenerated: true 
                    };
                }
            });
            setPlanDraft(autoDraft);
        }
    }, [roomsData]);

    const publishMutation = useMutation({
        mutationFn: publishPlan,
        onSuccess: (res) => {
            toast.success(res.data.message);
            queryClient.invalidateQueries(['dailyDashboardPlan']); // רענון הנתונים
        },
        onError: () => toast.error('שגיאה בהפצת הסידור')
    });

    const updateDraft = (roomId, field, value) => {
        setPlanDraft(prev => ({
            ...prev,
            [roomId]: {
                ...prev[roomId],
                [field]: value
            }
        }));
    };

    const handlePublish = () => {
        // המרת הטיוטה למערך שהשרת מצפה לו
        const payload = Object.entries(planDraft).map(([roomId, data]) => ({
            roomId,
            action: data.action,
            note: data.note
        })).filter(item => item.action !== 'none' || (item.note && item.note.trim() !== ''));

        if (payload.length === 0) return toast("אין שינויים להפצה");

        if (window.confirm(`האם להפיץ סידור עבודה ל-${payload.length} חדרים?`)) {
            publishMutation.mutate({ plan: payload });
        }
    };

    // עזר ויזואלי לסטטוסים
    const getStatusLabel = (status) => {
        const map = {
            'arrival': { text: 'הגעה', color: 'text-blue-600 bg-blue-50' },
            'departure': { text: 'עזיבה', color: 'text-red-600 bg-red-50' },
            'stayover': { text: 'נשאר', color: 'text-amber-600 bg-amber-50' },
            'back_to_back': { text: 'תחלופה', color: 'text-purple-600 bg-purple-50' },
            'empty': { text: 'ריק', color: 'text-gray-400' }
        };
        return map[status] || map['empty'];
    };

    return (
        <div className="container mx-auto p-4 sm:p-6 min-h-screen bg-slate-50 space-y-6" dir="rtl">
            {/* Header */}
            <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white p-4 rounded-xl shadow-sm border border-slate-200">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                        <CalendarDays className="text-blue-600"/> סידור עבודה חכם
                    </h1>
                    <p className="text-slate-500 text-sm mt-1">המערכת מסמנת אוטומטית את הפעולות הנדרשות לפי ההזמנות.</p>
                </div>
                
                <div className="flex items-center gap-4 w-full md:w-auto">
                    <div className="flex flex-col">
                        <span className="text-xs text-gray-500">תאריך לסידור:</span>
                        <input type="date" value={selectedDate} onChange={e => setSelectedDate(e.target.value)} className="border rounded px-2 py-1 text-sm"/>
                    </div>
                    <Button onClick={handlePublish} disabled={publishMutation.isPending} className="bg-green-600 hover:bg-green-700 shadow-md">
                        {publishMutation.isPending ? <RefreshCw className="animate-spin ml-2"/> : <Save className="ml-2"/>}
                        הפץ לחדרניות
                    </Button>
                </div>
            </header>

            {/* בחירת מלון */}
            <Tabs value={selectedHotel} onValueChange={setSelectedHotel} className="w-full">
                <TabsList className="bg-white p-1 border w-full justify-start overflow-x-auto h-auto">
                    {hotels.map(hotel => (
                        <TabsTrigger key={hotel._id} value={hotel._id} className="data-[state=active]:bg-blue-50 data-[state=active]:text-blue-700 px-4 py-2">
                            <Hotel className="w-4 h-4 ml-2"/> {hotel.name}
                        </TabsTrigger>
                    ))}
                </TabsList>

                <TabsContent value={selectedHotel || 'none'}>
                    <Card>
                        <CardContent className="p-0">
                            {isLoading ? (
                                <div className="p-10 text-center text-gray-500">טוען נתונים...</div>
                            ) : roomsData.length === 0 ? (
                                <div className="p-10 text-center text-gray-500">אין חדרים במלון זה.</div>
                            ) : (
                                <div className="overflow-x-auto">
                                    <table className="w-full text-sm text-right">
                                        <thead className="bg-slate-50 text-slate-600 border-b">
                                            <tr>
                                                <th className="p-4 w-20">חדר</th>
                                                <th className="p-4 w-32">סטטוס (אקסל)</th>
                                                <th className="p-4 w-32">מצב נוכחי</th>
                                                <th className="p-4 w-48">פעולה לביצוע</th>
                                                <th className="p-4">הערות לחדרנית</th>
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-slate-100">
                                            {roomsData.map(room => {
                                                const draft = planDraft[room._id] || {};
                                                const statusMeta = getStatusLabel(room.dashboardStatus);
                                                const isActionSelected = draft.action && draft.action !== 'none';

                                                return (
                                                    <tr key={room._id} className={`hover:bg-blue-50/10 transition-colors ${isActionSelected ? 'bg-blue-50/30' : ''}`}>
                                                        <td className="p-4 font-bold text-lg">{room.roomNumber}</td>
                                                        
                                                        {/* סטטוס מהאקסל */}
                                                        <td className="p-4">
                                                            <span className={`px-2 py-1 rounded text-xs font-bold border border-transparent ${statusMeta.color}`}>
                                                                {statusMeta.text}
                                                            </span>
                                                        </td>

                                                        {/* מצב פיזי של החדר */}
                                                        <td className="p-4 text-gray-500">
                                                            {room.status === 'clean' ? '✅ נקי' : 
                                                             room.status === 'maintenance' ? '🔧 תקול' : '🧹 מלוכלך'}
                                                        </td>

                                                        {/* בחירת פעולה (אוטומטית!) */}
                                                        <td className="p-4">
                                                            <Select 
                                                                value={draft.action || 'none'} 
                                                                onValueChange={(val) => updateDraft(room._id, 'action', val)}
                                                            >
                                                                <SelectTrigger className={`h-9 border-slate-200 ${isActionSelected ? 'border-blue-500 ring-1 ring-blue-200 bg-white' : 'bg-slate-50'}`}>
                                                                    <SelectValue placeholder="ללא פעולה" />
                                                                </SelectTrigger>
                                                                <SelectContent>
                                                                    <SelectItem value="none">-- ללא שינוי --</SelectItem>
                                                                    <SelectItem value="checkout">עזיבה / הכנה</SelectItem>
                                                                    <SelectItem value="stayover">נשאר (ניקיון)</SelectItem>
                                                                    <SelectItem value="arrival">כניסה (וידוא)</SelectItem>
                                                                </SelectContent>
                                                            </Select>
                                                            {draft.autoGenerated && <span className="text-[10px] text-blue-400 flex items-center gap-1 mt-1"><Wand2 size={10}/> זוהה אוטומטית</span>}
                                                        </td>

                                                        {/* הערות ידניות */}
                                                        <td className="p-4">
                                                            <Input 
                                                                placeholder="הוסף הערה..." 
                                                                value={draft.note || ''}
                                                                onChange={(e) => updateDraft(room._id, 'note', e.target.value)}
                                                                className="bg-transparent border-transparent hover:border-slate-200 focus:bg-white transition-all"
                                                            />
                                                        </td>
                                                    </tr>
                                                );
                                            })}
                                        </tbody>
                                    </table>
                                </div>
                            )}
                        </CardContent>
                    </Card>
                </TabsContent>
            </Tabs>
        </div>
    );
}